### PR TITLE
Feature/config refactor

### PR DESCRIPTION
**Pull request by yxdyc**
refactored the configuration and aligned to the open-source version

- split config into several sub configs
- implement a new CfgNode class with re-organized assert, freeze, etc.,
- replaced the project name and fixed several errors introduced by the rebase process

Plz double check the modifications between the open-source version and master from gitlab

### CODE REVIEW

**Review by xieyxclack — CHANGES_REQUESTED** [review]
Please refer to the inline comments for minor suggestions, others looks good to me

**Review by xieyxclack — APPROVED** [review]

**Review by xieyxclack — APPROVED** [review]
LGTM

**Review by rayrayraykk — APPROVED** [review]
Looks good to me.

**Comment by DavdGao** [comment]
It looks good to me

**Review by joneswong — APPROVED** [review]
Approve!

**Pull request merged**
