### PR TITLE
[HotFix] Fix contrib.

### PR DESCRIPTION
**Pull request by rayrayraykk**
As the title says, could not use external file in `contrib`.

### CODE REVIEW

**Review by joneswong — COMMENTED** [review]
looks good. why do we need try-catch here?

**Comment by rayrayraykk** [comment]
> looks good. why do we need try-catch here?

We may add more examples, such as data from PYG, to the `contrib` in the future, but some examples are not available for users who have the minimal version installed.

**Comment by joneswong** [comment]
sounds reasonable...but why not let people know what happened. For example, if the failure of importing is caused by my incorrect implementation.

**Review by joneswong — APPROVED** [review]
approved.

**Pull request merged**
